### ISSUE TITLE
How do US based RSEs participate?

### ISSUE THREAD

**Issue by vsoch** [research-software-reactor/research-software-reactor.github.io#1]
hey @ggorman ! I absolutely love this idea - documentation is overlooked and especially not catered for the academic / research cohort. 

I'm a US based RSE, and there are a few groups similar to the UK Research Software Engineer Association, but not quite as established ([the [ussri](http://urssi.us/) is focused on sustainability and only has reached out to a small number]. On the other hand, I know of teams at Princeton, a growing team at Harvard, and then scattered individuals like myself that do a lot of work in the cloud, and also care about software engineering for science.

How do we participate too?

**Comment by trallard** [comment]
I only just saw this @vsoch  apologies!
We are planning to run similar events in the USA next year, maybe if you drop me a line to my email I can keep you posted when we have more details

**Comment by vsoch** [comment]
Will do! We now are working on usrse (the UK equivalent) so likely we can bring in many folks!

 - https://www.github.com/usrse
 - https://www.twitter.com/us_rse

I'll send this all in an email.
